"use client"

import './globals.css'
import CanvasModel from "@/canvas";


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <main className={"app transition-all ease-in"}>
            {children}
            <CanvasModel/>
        </main>
        </body>
        </html>
    )
}
